CREATE OR ALTER TRIGGER [dbo].[TR_PLAN_DETAIL_SYNC_TARGET_PROD]
ON [dbo].[TB_H_PROD_PLAN_DETAIL]
AFTER INSERT, UPDATE
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @PlanDeltas TABLE (
        FTYPE_BATTERY varchar(20),
        FMODEL_BATTERY varchar(30),
        ORDER_TYPE nvarchar(50),
        DeltaQty int
    );

    INSERT INTO @PlanDeltas (FTYPE_BATTERY, FMODEL_BATTERY, ORDER_TYPE, DeltaQty)
    SELECT
                COALESCE(pm.FTYPE_BATTERY, mapType.FTYPE_BATTERY) AS FTYPE_BATTERY,
        pm.FMODEL_BATTERY,
        i.ORDER_TYPE,
        i.QTY_PLAN - CASE
            WHEN ISNULL(d.SEQ_GENERATED, 0) = 1 THEN ISNULL(d.QTY_PLAN, 0)
            ELSE 0
        END AS DeltaQty
    FROM inserted i
    LEFT JOIN deleted d ON d.FID = i.FID
    JOIN TB_M_PROD_MODEL pm ON UPPER(pm.FMODEL_BATTERY) = UPPER(i.MODEL_NAME)
        OUTER APPLY (
                SELECT TOP 1 m.FTYPE_BATTERY
                FROM TB_M_BATTERY_MAPPING m
                WHERE UPPER(m.FMODEL_BATTERY) = UPPER(i.MODEL_NAME)
                    AND m.FTYPE_BATTERY IS NOT NULL
                ORDER BY m.FTYPE_BATTERY
        ) mapType
    WHERE i.ORDER_TYPE <> 'Assy'
      AND ISNULL(i.SEQ_GENERATED, 0) = 1
            AND COALESCE(pm.FTYPE_BATTERY, mapType.FTYPE_BATTERY) IS NOT NULL
      AND pm.FMODEL_BATTERY IS NOT NULL;

    INSERT INTO TB_R_TARGET_PROD (FTYPE_BATTERY, FMODEL_BATTERY, ORDER_TYPE, FTARGET, FDATETIME_MODIFIED)
    SELECT DISTINCT p.FTYPE_BATTERY, p.FMODEL_BATTERY, p.ORDER_TYPE, 0, GETDATE()
    FROM @PlanDeltas p
    WHERE NOT EXISTS (
        SELECT 1
        FROM TB_R_TARGET_PROD t
        WHERE t.FTYPE_BATTERY = p.FTYPE_BATTERY
          AND t.FMODEL_BATTERY = p.FMODEL_BATTERY
    );

    UPDATE t
    SET
        t.FTARGET = t.FTARGET + p.DeltaQty,
        t.ORDER_TYPE = p.ORDER_TYPE,
        t.FPROD_DATE = CAST(GETDATE() AS DATE),
        t.FDATETIME_MODIFIED = GETDATE()
    FROM TB_R_TARGET_PROD t
    JOIN @PlanDeltas p
      ON t.FTYPE_BATTERY = p.FTYPE_BATTERY
     AND t.FMODEL_BATTERY = p.FMODEL_BATTERY
    WHERE p.DeltaQty <> 0;
END;
GO
