USE [DB_TMMIN1_KRW_PIS_HV_BATTERY]
GO

SET NOCOUNT ON;
GO

-- Normalize ORDER_TYPE values to canonical uppercase format.
-- Canonical values:
-- 1) ASSY
-- 2) CKD
-- 3) SERVICE PART

IF COL_LENGTH('dbo.TB_M_PROD_ORDER_TYPE', 'ORDER_TYPE') IS NOT NULL
BEGIN
  UPDATE t
  SET ORDER_TYPE =
    CASE
      WHEN UPPER(LTRIM(RTRIM(ISNULL(t.ORDER_TYPE, '')))) = 'ASSY' THEN 'ASSY'
      WHEN UPPER(LTRIM(RTRIM(ISNULL(t.ORDER_TYPE, '')))) = 'CKD' THEN 'CKD'
      WHEN UPPER(LTRIM(RTRIM(ISNULL(t.ORDER_TYPE, '')))) IN ('SERVICE PART', 'SERVICE_PART', 'SERVICEPART') THEN 'SERVICE PART'
      ELSE UPPER(LTRIM(RTRIM(t.ORDER_TYPE)))
    END
  FROM dbo.TB_M_PROD_ORDER_TYPE t
  WHERE t.ORDER_TYPE IS NOT NULL;

  PRINT '+ TB_M_PROD_ORDER_TYPE.ORDER_TYPE normalized';
END
GO

IF COL_LENGTH('dbo.TB_M_BATTERY_MAPPING', 'ORDER_TYPE') IS NOT NULL
BEGIN
  UPDATE t
  SET ORDER_TYPE =
    CASE
      WHEN UPPER(LTRIM(RTRIM(ISNULL(t.ORDER_TYPE, '')))) = 'ASSY' THEN 'ASSY'
      WHEN UPPER(LTRIM(RTRIM(ISNULL(t.ORDER_TYPE, '')))) = 'CKD' THEN 'CKD'
      WHEN UPPER(LTRIM(RTRIM(ISNULL(t.ORDER_TYPE, '')))) IN ('SERVICE PART', 'SERVICE_PART', 'SERVICEPART') THEN 'SERVICE PART'
      ELSE UPPER(LTRIM(RTRIM(t.ORDER_TYPE)))
    END
  FROM dbo.TB_M_BATTERY_MAPPING t
  WHERE t.ORDER_TYPE IS NOT NULL;

  PRINT '+ TB_M_BATTERY_MAPPING.ORDER_TYPE normalized';
END
GO

IF COL_LENGTH('dbo.TB_M_INIT_QRCODE', 'ORDER_TYPE') IS NOT NULL
BEGIN
  UPDATE t
  SET ORDER_TYPE =
    CASE
      WHEN UPPER(LTRIM(RTRIM(ISNULL(t.ORDER_TYPE, '')))) = 'ASSY' THEN 'ASSY'
      WHEN UPPER(LTRIM(RTRIM(ISNULL(t.ORDER_TYPE, '')))) = 'CKD' THEN 'CKD'
      WHEN UPPER(LTRIM(RTRIM(ISNULL(t.ORDER_TYPE, '')))) IN ('SERVICE PART', 'SERVICE_PART', 'SERVICEPART') THEN 'SERVICE PART'
      ELSE UPPER(LTRIM(RTRIM(t.ORDER_TYPE)))
    END
  FROM dbo.TB_M_INIT_QRCODE t
  WHERE t.ORDER_TYPE IS NOT NULL;

  PRINT '+ TB_M_INIT_QRCODE.ORDER_TYPE normalized';
END
GO

IF COL_LENGTH('dbo.TB_R_TARGET_PROD', 'ORDER_TYPE') IS NOT NULL
BEGIN
  UPDATE t
  SET ORDER_TYPE =
    CASE
      WHEN UPPER(LTRIM(RTRIM(ISNULL(t.ORDER_TYPE, '')))) = 'ASSY' THEN 'ASSY'
      WHEN UPPER(LTRIM(RTRIM(ISNULL(t.ORDER_TYPE, '')))) = 'CKD' THEN 'CKD'
      WHEN UPPER(LTRIM(RTRIM(ISNULL(t.ORDER_TYPE, '')))) IN ('SERVICE PART', 'SERVICE_PART', 'SERVICEPART') THEN 'SERVICE PART'
      WHEN UPPER(LTRIM(RTRIM(ISNULL(t.ORDER_TYPE, '')))) IN ('INJECT MAN - ASSY', 'INJECT MAN-ASSY') THEN 'INJECT MAN - ASSY'
      WHEN UPPER(LTRIM(RTRIM(ISNULL(t.ORDER_TYPE, '')))) IN ('INJECT MAN - CKD', 'INJECT MAN-CKD') THEN 'INJECT MAN - CKD'
      WHEN UPPER(LTRIM(RTRIM(ISNULL(t.ORDER_TYPE, '')))) IN ('INJECT MAN - SERVICE PART', 'INJECT MAN-SERVICE PART', 'INJECT MAN - SERVICE_PART') THEN 'INJECT MAN - SERVICE PART'
      ELSE UPPER(LTRIM(RTRIM(t.ORDER_TYPE)))
    END
  FROM dbo.TB_R_TARGET_PROD t
  WHERE t.ORDER_TYPE IS NOT NULL;

  PRINT '+ TB_R_TARGET_PROD.ORDER_TYPE normalized';
END
GO

IF COL_LENGTH('dbo.TB_R_SEQUENCE_BATTERY', 'ORDER_TYPE') IS NOT NULL
BEGIN
  UPDATE t
  SET ORDER_TYPE =
    CASE
      WHEN UPPER(LTRIM(RTRIM(ISNULL(t.ORDER_TYPE, '')))) = 'ASSY' THEN 'ASSY'
      WHEN UPPER(LTRIM(RTRIM(ISNULL(t.ORDER_TYPE, '')))) = 'CKD' THEN 'CKD'
      WHEN UPPER(LTRIM(RTRIM(ISNULL(t.ORDER_TYPE, '')))) IN ('SERVICE PART', 'SERVICE_PART', 'SERVICEPART') THEN 'SERVICE PART'
      WHEN UPPER(LTRIM(RTRIM(ISNULL(t.ORDER_TYPE, '')))) IN ('INJECT MAN - ASSY', 'INJECT MAN-ASSY') THEN 'INJECT MAN - ASSY'
      WHEN UPPER(LTRIM(RTRIM(ISNULL(t.ORDER_TYPE, '')))) IN ('INJECT MAN - CKD', 'INJECT MAN-CKD') THEN 'INJECT MAN - CKD'
      WHEN UPPER(LTRIM(RTRIM(ISNULL(t.ORDER_TYPE, '')))) IN ('INJECT MAN - SERVICE PART', 'INJECT MAN-SERVICE PART', 'INJECT MAN - SERVICE_PART') THEN 'INJECT MAN - SERVICE PART'
      ELSE UPPER(LTRIM(RTRIM(t.ORDER_TYPE)))
    END
  FROM dbo.TB_R_SEQUENCE_BATTERY t
  WHERE t.ORDER_TYPE IS NOT NULL;

  PRINT '+ TB_R_SEQUENCE_BATTERY.ORDER_TYPE normalized';
END
GO

PRINT 'DONE: ORDER_TYPE values normalized to uppercase canonical format.';
GO
