-- Add FMODEL_BATTERY column to TB_R_MAN_BRACKET

IF COL_LENGTH('dbo.TB_R_MAN_BRACKET', 'FMODEL_BATTERY') IS NULL
BEGIN
    ALTER TABLE [dbo].[TB_R_MAN_BRACKET]
    ADD [FMODEL_BATTERY] VARCHAR(20) NULL

    PRINT 'Column FMODEL_BATTERY added to TB_R_MAN_BRACKET.'
END
ELSE
BEGIN
    PRINT 'Column FMODEL_BATTERY already exists in TB_R_MAN_BRACKET.'
END
