-- Add PROD_DATE and SHIFT columns to TB_R_MAN_BRACKET

IF COL_LENGTH('dbo.TB_R_MAN_BRACKET', 'PROD_DATE') IS NULL
BEGIN
    ALTER TABLE [dbo].[TB_R_MAN_BRACKET]
    ADD [PROD_DATE] DATE NULL

    PRINT 'Column PROD_DATE added to TB_R_MAN_BRACKET.'
END
ELSE
BEGIN
    PRINT 'Column PROD_DATE already exists in TB_R_MAN_BRACKET.'
END

IF COL_LENGTH('dbo.TB_R_MAN_BRACKET', 'SHIFT') IS NULL
BEGIN
    ALTER TABLE [dbo].[TB_R_MAN_BRACKET]
    ADD [SHIFT] VARCHAR(50) NULL

    PRINT 'Column SHIFT added to TB_R_MAN_BRACKET.'
END
ELSE
BEGIN
    PRINT 'Column SHIFT already exists in TB_R_MAN_BRACKET.'
END
