-- Replace cursor-based trigger with set-based MERGE
CREATE OR ALTER TRIGGER TRG_M_STATION_CONFIG_UPDATE
ON TB_M_STATION_CONFIG
AFTER UPDATE
AS
BEGIN
  SET NOCOUNT ON;

  DECLARE @prefix VARCHAR(10);
  SELECT @prefix = CASE
    WHEN EXISTS (SELECT 1 FROM TB_M_STATION_CONFIG WHERE STATION_NAME = 'MAN_ASSY_5' AND IS_ACTIVE = 1) THEN '3'
    WHEN EXISTS (SELECT 1 FROM TB_M_STATION_CONFIG WHERE STATION_NAME = 'MAN_ASSY_4' AND IS_ACTIVE = 1) THEN '2'
    ELSE '1'
  END;

  DECLARE @a4 BIT = (SELECT IS_ACTIVE FROM TB_M_STATION_CONFIG WHERE STATION_NAME = 'MAN_ASSY_4');
  DECLARE @a5 BIT = (SELECT IS_ACTIVE FROM TB_M_STATION_CONFIG WHERE STATION_NAME = 'MAN_ASSY_5');

  MERGE TB_R_RFID_COMMAND AS t
  USING (
    SELECT STATION_NAME, CMD, computed_id
    FROM TB_M_STATION_CONFIG
    CROSS APPLY (
      VALUES ('READ'), ('WRITE')
    ) AS cmds(CMD)
    CROSS APPLY (
      VALUES (
        CASE
          WHEN IS_MANDATORY = 1 THEN @prefix + '_' + STATION_ID_SUFFIX
          WHEN STATION_NAME = 'MAN_ASSY_4' AND @a4 = 1 THEN @prefix + '_' + STATION_ID_SUFFIX
          WHEN STATION_NAME = 'MAN_ASSY_5' AND @a5 = 1 THEN @prefix + '_' + STATION_ID_SUFFIX
          ELSE NULL
        END
      )
    ) AS ids(computed_id)
  ) AS s ON t.STATION_NAME = s.STATION_NAME AND t.COMMAND = s.CMD
  WHEN MATCHED THEN
    UPDATE SET STATION_ID = s.computed_id, FDATETIME_MODIFIED = GETDATE()
  WHEN NOT MATCHED BY TARGET THEN
    INSERT (STATION_NAME, STATION_ID, COMMAND, FVALUE, FDATETIME_MODIFIED)
    VALUES (s.STATION_NAME, s.computed_id, s.CMD, 0, GETDATE());
END;
GO
