USE [DB_TMMIN1_KRW_PIS_HV_BATTERY]
GO
SET NOCOUNT ON;

BEGIN TRAN;

DECLARE @fid INT;
DECLARE @type NVARCHAR(100);
DECLARE @model NVARCHAR(100);
DECLARE @orderType NVARCHAR(100);
DECLARE @prodDate DATE;
DECLARE @beforeCount INT;
DECLARE @afterCount INT;

SELECT TOP (1)
    @fid = t.FID,
    @type = t.FTYPE_BATTERY,
    @model = t.FMODEL_BATTERY,
    @orderType = t.ORDER_TYPE,
    @prodDate = CAST(ISNULL(t.FPROD_DATE, GETDATE()) AS DATE)
FROM dbo.TB_R_TARGET_PROD t
ORDER BY t.FID DESC;

SELECT
    @beforeCount = COUNT(*)
FROM dbo.TB_R_SEQUENCE_BATTERY s
WHERE RTRIM(LTRIM(s.FTYPE_BATTERY)) = RTRIM(LTRIM(@type))
  AND RTRIM(LTRIM(s.FMODEL_BATTERY)) = RTRIM(LTRIM(@model))
  AND CAST(s.FSEQ_DATE AS DATE) = @prodDate
  AND s.FSTATUS = 0;

PRINT 'TEST TARGET ROW';
SELECT @fid AS FID, @type AS FTYPE_BATTERY, @model AS FMODEL_BATTERY, @orderType AS ORDER_TYPE, @prodDate AS PROD_DATE;

UPDATE dbo.TB_R_TARGET_PROD
SET FTARGET = ISNULL(FTARGET, 0) + 1,
    FDATETIME_MODIFIED = GETDATE()
WHERE FID = @fid;

SELECT
    @afterCount = COUNT(*)
FROM dbo.TB_R_SEQUENCE_BATTERY s
WHERE RTRIM(LTRIM(s.FTYPE_BATTERY)) = RTRIM(LTRIM(@type))
  AND RTRIM(LTRIM(s.FMODEL_BATTERY)) = RTRIM(LTRIM(@model))
  AND CAST(s.FSEQ_DATE AS DATE) = @prodDate
  AND s.FSTATUS = 0;

PRINT 'DELTA ROWS INSERTED';
SELECT @beforeCount AS BEFORE_COUNT, @afterCount AS AFTER_COUNT, (@afterCount - @beforeCount) AS INSERTED_DELTA;

PRINT 'LATEST ROWS FOR SAME TYPE+MODEL+DATE';
SELECT TOP (10)
    s.FID,
    s.FID_ADJUST,
    s.FTYPE_BATTERY,
    s.FMODEL_BATTERY,
    s.ORDER_TYPE,
    s.FSEQ_NO,
    s.FSEQ_DATE,
    s.FSTATUS,
    s.FBARCODE
FROM dbo.TB_R_SEQUENCE_BATTERY s
WHERE RTRIM(LTRIM(s.FTYPE_BATTERY)) = RTRIM(LTRIM(@type))
  AND RTRIM(LTRIM(s.FMODEL_BATTERY)) = RTRIM(LTRIM(@model))
  AND CAST(s.FSEQ_DATE AS DATE) = @prodDate
ORDER BY s.FID DESC;

PRINT 'DUPLICATE CHECK PER SEQ_NO (SAME TYPE+MODEL+DATE, FSTATUS=0)';
SELECT
    s.FSEQ_NO,
    COUNT(*) AS DUP_COUNT
FROM dbo.TB_R_SEQUENCE_BATTERY s
WHERE RTRIM(LTRIM(s.FTYPE_BATTERY)) = RTRIM(LTRIM(@type))
  AND RTRIM(LTRIM(s.FMODEL_BATTERY)) = RTRIM(LTRIM(@model))
  AND CAST(s.FSEQ_DATE AS DATE) = @prodDate
  AND s.FSTATUS = 0
GROUP BY s.FSEQ_NO
HAVING COUNT(*) > 1
ORDER BY s.FSEQ_NO;

ROLLBACK TRAN;
GO
